
name: build
on:
  push:
  workflow_dispatch:
    inputs:
      version_type:
        description: "The type of this version. e.g alpha"
        type: choice
        default: beta
        options:
          - release
          - beta
          - alpha
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ci skip]')
    outputs:
      version_info: ${{ steps.get_version.outputs.version_info }}
      version_plain: ${{ steps.get_version.outputs.version_plain }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.1
      - name: setup jdk 21
        uses: actions/setup-java@v4.1.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build and check
        run: |
          ./gradlew check build spotbugs

      - name: get version #https://stackoverflow.com/questions/71089787/how-to-get-version-name-from-android-gradle-file-in-github-actions
        run: |
          echo "version_info=$(${{github.workspace}}/gradlew -q printVersionName)" >> $GITHUB_OUTPUT
          echo "version_plain=$(${{github.workspace}}/gradlew -q printVersion)" >> $GITHUB_OUTPUT
      - name: capture build artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Artifacts
          path: build/libs/

      - name: set up reviewdog
        uses: reviewdog/action-setup@v1
      - name: upload spotbugs sarif report
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat ./build/reports/spotbugs/main/spotbugs.sarif | reviewdog -name="spotbugs" -f=sarif -reporter=github-check -level=warning

      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew publish

  client_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4.1.1
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.1
      - name: setup jdk 21
        uses: actions/setup-java@v4.1.0
        with:
          distribution: 'temurin'
          java-version: 21
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: run testmod
        uses: modmuss50/xvfb-action@v1
        with:
          run: ./gradlew runAutoTest --stacktrace --warning-mode=fail
      - uses: actions/upload-artifact@v4.3.1
        with:
          name: Test Screenshots
          path: run/screenshots

  publish:
    needs:
      - build
      - client_test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4.1.1
      - uses: actions/download-artifact@v4.1.4
        with:
          name: Artifacts
          path: build/libs

      - name: publish release
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          version-type: ${{ inputs.version_type }}
          changelog: https://github.com/melontini/dark-matter/blob/${{ github.sha }}/CHANGELOG.md
          name: ${{ needs.build.outputs.version_info }}
          version: ${{ needs.build.outputs.version_plain }}

          game-versions: |
            1.20.4

          loaders: |
            fabric

          java: |
            21

          github-tag: ${{ needs.build.outputs.version_plain }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-commitish: ${{ github.sha }}
          github-prerelease: false

          modrinth-id: qcz8IJ9L
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          modrinth-unfeature-mode: subset

          curseforge-id: 839908
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}